### ISSUE TITLE
Running Demo on Android P: "Failed to acquire new image, due to too many images acquired but not released"

### ISSUE THREAD

**Issue by lkuich** [8thwall/xr-unity#47]
Hey, I'm trying to run the quickstart Demo app using Unity 2018.1.2f1, using 8th Wall XR 7.1.3.241, targeting my Google Pixel running Android P. I followed each step, closed the XR Panel, entered my API credentials and all.

I'm not getting anything on my device, I see the camera and nothing showing up, in the logcat I get the following error repeatedly:
```
06-03 19:48:19.405 17947 17987 E native  : cpu_image_manager.cc:102 Failed to acquire new image, due to too many images acquired but not released.
06-03 19:48:19.405 17947 17987 E native  : status.cc:158 ArStatusErrorSpace::AR_ERROR_RESOURCE_EXHAUSTED:
06-03 19:48:19.408 17947 17987 E Unity   : AndroidJavaException: com.google.ar.core.exceptions.ResourceExhaustedException
06-03 19:48:19.408 17947 17987 E Unity   : com.google.ar.core.exceptions.ResourceExhaustedException
06-03 19:48:19.408 17947 17987 E Unity   :      at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:94)
06-03 19:48:19.408 17947 17987 E Unity   :      at com.google.ar.core.Frame.nativeAcquireCameraImage(Native Method)
06-03 19:48:19.408 17947 17987 E Unity   :      at com.google.ar.core.Frame.acquireCameraImage(Unknown Source:6)
06-03 19:48:19.408 17947 17987 E Unity   :      at com.the8thwall.reality.app.xr.android.d.a(Unknown Source:840)
06-03 19:48:19.408 17947 17987 E Unity   :      at com.the8thwall.reality.app.xr.android.d.b(Unknown Source:38)
06-03 19:48:19.408 17947 17987 E Unity   :      at com.the8thwall.reality.app.xr.android.XRAndroid.getCurrentRealityXR(Unknown Source:5)
06-03 19:48:19.408 17947 17987 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
06-03 19:48:19.408 17947 17987 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
06-03 19:48:19.408 17947 17987 E Unity   :      at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source:151)
06-03 19:48:19.408 17947 17987 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)
06-03 19:48:19.408 17947 17987 E Unity   :      at android.os.Looper.loop(Looper.java:164)
06-03 19:48:19.408 17947 17987 E Unity   :      at com.unity3d.player.UnityPlayer$c.run(Unknown Source:20)
06-03 19:48:19.408 17947 17987 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0
06-03 19:48:19.408 17947 17987 E Unity   :   at UnityEngine.```

**Comment by mralbean** [comment]
Thanks for reporting this!

I've been able to reproduce your error on a Pixel 2 running on Android P. Looks like this is stemming from an issue with how ARCore is creating their image plane data on Android P devices:

```
06-04 12:09:48.770 12070 12093 W all.HelloOrigi: Accessing hidden method Landroid/media/Image$Plane;-><init>()V (blacklist, linking)
06-04 12:09:48.771 12070 12093 W all.HelloOrigi: Accessing hidden method Landroid/media/Image$Plane;-><init>()V (blacklist, linking)
06-04 12:09:48.800 12070 12093 E Unity   : AndroidJavaException: java.lang.NoSuchMethodError: No direct method <init>()V in class Landroid/media/Image$Plane; or its super classes (declaration of 'android.media.Image$Plane' appears in /system/framework/framework.jar)
06-04 12:09:48.800 12070 12093 E Unity   : java.lang.NoSuchMethodError: No direct method <init>()V in class Landroid/media/Image$Plane; or its super classes (declaration of 'android.media.Image$Plane' appears in /system/framework/framework.jar)
06-04 12:09:48.800 12070 12093 E Unity   : 	at a.a.b.<init>(Unknown Source:0)
06-04 12:09:48.800 12070 12093 E Unity   : 	at com.google.ar.core.c.<init>(Unknown Source:2)
06-04 12:09:48.800 12070 12093 E Unity   : 	at com.google.ar.core.ArImage.getPlanes(Unknown Source:26)
06-04 12:09:48.800 12070 12093 E Unity   : 	at com.the8thwall.reality.app.xr.android.d.a(Unknown Source:775)
06-04 12:09:48.800 12070 12093 E Unity   : 	at com.the8thwall.reality.app.xr.android.d.b(Unknown Source:38)
06-04 12:09:48.800 12070 12093 E Unity   : 	at com.the8thwall.reality.app.xr.android.XRAndroid.getCurrentRealityXR(Unknown Source:5)
06-04 12:09:48.800 12070 12093 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
06-04 12:09:48.800 12070 12093 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
06-04 12:09:48.800 12070 12093 E Unity   : 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source:151)
06-04 12:09:48.800 12070 12093 E Unity   : 	at android.os.Handler.dispatchMessage(H
```

I've created an [issue](https://github.com/google-ar/arcore-android-sdk/issues/414) on the ARCore SDK GitHub repo to bring this to the ARCore team's attention. In the mean time, running on a device on Oreo should provide the expected experience.

**Comment by mralbean** [comment]
Hi @lkuich 

I just tested this out on an device running Android P Beta 2 (PPP3.180510.008). This issue now seems to be fixed!
